<?php

declare(strict_types=1);

use Infrangible\CatalogProductPrice\Block\Information;
use Magento\Framework\Escaper;

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Escaper $escaper */
/** @var Information $block */
?>

<span class="price-information">
    <span class="price-container price-information_price">
        <?php if ($block->hasData('display_label')): ?>
            <span class="price-label"><?= $escaper->escapeHtml($block->getData('display_label')); ?></span>
        <?php endif; ?>
        <?php if ($block->hasData('amount')): ?>
            <span data-price-amount="<?= $escaper->escapeHtmlAttr($block->getData('amount')); ?>"
                  data-price-type="price_information"
                  class="price-wrapper"
            >
                <?= $escaper->escapeHtml($block->formatCurrency($block->getData('amount'), (bool) $block->getData('include_container')), ['span']); ?>
            </span>
        <?php endif; ?>
        <?php if ($block->hasData('information')): ?>
            <span class="price-information"><?= $block->getData('information'); ?></span>
        <?php endif; ?>
    </span>
</span>
