<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */
?>

<script type="text/x-magento-template" id="catalog-product-price-information-template">
    <span class="price-container price-information_price">
        <% if (displayLabel) { %>
            <span class="price-label"><%- displayLabel %></span>
        <% } %>
        <% if (amount) { %>
            <span data-price-amount="<%- amountValue %>"
                  data-price-type="price_information"
                  class="price-wrapper"
            >
                <span class="price"><%- amount %></span>
            </span>
        <% } %>
        <% if (information) { %>
            <span class="price-information"><%- information %></span>
        <% } %>
    </span>
</script>
