<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductPrice\Block\SpecialPrice;

/** @var SpecialPrice $block */

$priceModel = $block->getPriceType('regular_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
?>

<span class="old-price sly-old-price">
    <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
        'display_label'     => __('Regular Price'),
        'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
        'price_type'        => 'oldPrice',
        'include_container' => true,
        'skip_adjustments'  => true
    ]); ?>
</span>
